# 配置网关
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**  # 访问user路径转发用户服务
        - id: product-service # 此名称随意定义
          uri: lb://product-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/product/** # 访问product相关,转发到product服务
        - id: static-service # 此名称随意定义
          uri: lb://static-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/public/** # 访问静态资源相关,转发到静态资源服务
        - id: carousel-service # 轮播图服务
          uri: lb://carousel-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/carousel/** # 访问静态资源相关,转发到静态资源服务
        - id: product-service # 商品服务
          uri: lb://product-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/product/** # 访问静态资源相关,转发到静态资源服务
        - id: category-service # 分类服务
          uri: lb://category-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/category/** # 访问静态资源相关,转发到静态资源服务
        - id: search-service # 搜索服务
          uri: lb://search-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/search/** # 访问静态资源相关,转发到静态资源服务
        - id: collect-service # 收藏服务
          uri: lb://collect-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/collect/** # 访问静态资源相关,转发到静态资源服务
        - id: cart-service  # 收藏服务
          uri: lb://cart-service  #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/cart/** # 访问静态资源相关,转发到静态资源服务
        - id: order-service  # 订单服务
          uri: lb://order-service  #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/order/** # 访问静态资源相关,转发到静态资源服务
        - id: admin-service  # 后台服务
          uri: lb://admin-service  #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/admin/** # 访问静态资源相关,转发到静态资源服务

